export const Constants = {
  DUPLICATE_TRANSACTION_BUFFER_TIME:10,
  MATCHING_TRANSACTION_BUFFER_TIME:2880,
  CUTOFF_DUPLICATE_TRANS_DESCRIPTION_CONFIDENCE:90,
  CUTOFF_MATCHING_TRANS_REFERENCE_CON:90,
  DEAFAULT_DUPLICATE_TRANS_DESCRIPTION_CONFIDENCE:50,
  DEFAULT_MATCHING_TRANS_REFERENCE_CON:50,
} as const