export enum AccountType {
  SAVINGS = "SAVINGS",
  CURRENT = "CURRENT",
  DEBITCARD="DEBITCARD",
  CREDITCARD = "CREDITCARD",
  WALLET = "WALLET",
  MOBILE_BILL="MOBILE_BILL",
  ELECTRIC_BILL = "ELECTRIC_BILL",
  GAS_BILL="GAS_BILL",
  INSURANCE="INSURANCE",
  LOAN="LOAN",
  SUBSCRIPTION="SUBSCRIPTION",
  WALLET_PPI="WALLET_PPI",
  FOREX_CARDS="FOREXCARDS"
}