export enum MessageType {
  DEBIT ="DEBIT",
  CREDIT = "CREDIT",
  REMINDER="REMINDER",
  CC_REPAYMENT = "CC_REPAYMENT",
  BILL_PAYMENT = "BILL_PAYMENT",
  CC_STATEMENT="CC_STATEMENT",
  BILL_STATEMENT="BILL_STATEMENT",
  INFORMATION="INFORMATION"
}
